# new-mod.ps1 — scaffold a fresh Maker Studio mod folder.
#
# Usage:
#   .\scripts\new-mod.ps1
#   .\scripts\new-mod.ps1 -ModId com.yourname.mymod -Name "My Mod" -Author "Your Name"
#
# Creates ./<short-name>/ with:
#   manifest.json   filled in with your id/name/author + apiVersion + permissions stub
#   index.js        activate(ctx) skeleton with toast + menu item
#   README.md       starter doc with build + sign + release reminder

param(
    [string]$ModId = "",
    [string]$Name = "",
    [string]$Author = "",
    [string]$Description = "",
    [string]$OutDir = (Get-Location).Path
)

$ErrorActionPreference = "Stop"

function Read-Required([string]$Prompt) {
    while ($true) {
        $v = Read-Host $Prompt
        if ($v) { return $v }
        Write-Host "  (required — try again)" -ForegroundColor Yellow
    }
}

Write-Host ""
Write-Host "Maker Studio — new mod scaffolder" -ForegroundColor Cyan
Write-Host ""

if (-not $ModId)  { $ModId  = Read-Required "Mod id (reverse-DNS, e.g. com.yourname.mymod)" }
if (-not $Name)   { $Name   = Read-Required "Display name (shown in Mod Manager)" }
if (-not $Author) { $Author = Read-Required "Author (your display name)" }
if (-not $Description) {
    $Description = Read-Host "Description (one short sentence — optional, press Enter to skip)"
}

if ($ModId -notmatch '^[a-zA-Z0-9._-]+$') {
    Write-Host "Mod id has invalid characters. Allowed: letters, digits, '.', '_', '-'." -ForegroundColor Red
    exit 1
}
if ($ModId -notmatch '\.') {
    Write-Host "Mod id should look reverse-DNS (must contain at least one '.', e.g. com.yourname.mymod)." -ForegroundColor Yellow
}

# Use the last segment of the mod id as the folder name (e.g. com.toskan4134.hello-world → hello-world).
$ShortName = ($ModId -split '\.')[-1]
$Target = Join-Path $OutDir $ShortName

if (Test-Path $Target) {
    Write-Host "Target already exists: $Target" -ForegroundColor Red
    Write-Host "Move/remove it before re-running. Refusing to overwrite." -ForegroundColor Red
    exit 1
}

New-Item -ItemType Directory -Path $Target | Out-Null

# manifest.json
$manifest = [ordered]@{
    id          = $ModId
    name        = $Name
    version     = "1.0.0"
    author      = $Author
    description = $Description
    apiVersion  = "1.0.0"
    main        = "index.js"
    permissions = @("ui.toasts")
}
$manifest | ConvertTo-Json -Depth 4 | Out-File -FilePath (Join-Path $Target "manifest.json") -Encoding utf8

# index.js
$indexJs = @"
/**
 * $Name — $Description
 * Generated by scripts/new-mod.ps1.
 */

export function activate(ctx) {
  ctx.log.info("$Name activated");

  ctx.ui.showToast({
    message: "Hello from $Name!",
    level: "info",
  });

  ctx.menu.registerMenuItem({
    menu: "Mods",
    label: "$Name — Say Hi",
    handler: () => {
      ctx.ui.showToast({ message: "Hi from $Name!" });
    },
  });
}

export function deactivate() {
  // Disposables registered through ctx are auto-cleaned. Nothing else to do.
}
"@
$indexJs | Out-File -FilePath (Join-Path $Target "index.js") -Encoding utf8

# README.md
$readme = @"
# $Name

$Description

## Try it locally

1. Copy this folder into ``%APPDATA%/maker-studio/Mods/$ShortName/`` (global) or
   ``<gameRoot>/Plugins/MakerStudio/003_Editor/Mods/$ShortName/`` (project).
2. Restart the editor (or **Mods → Mod Manager → Rescan**).
3. Open any project — toast appears, menu item shows up under **Mods**.

## Publish it

1. Push this folder to a public GitHub repo (one repo per mod).
2. Tag ``v1.0.0`` (must match ``manifest.json#version``).
3. Build the release zip:
   ``````powershell
   Compress-Archive -Path manifest.json,index.js,README.md -DestinationPath $ModId-1.0.0.zip
   ``````
4. Sign it (see ``../KEYS.md`` for keypair setup):
   ``````powershell
   minisign -S -s your-mod.key -m $ModId-1.0.0.zip
   ``````
5. Create a GitHub Release for the tag, attach both files.
6. Open a PR to the [registry](https://github.com/Toskan4134/maker-studio-mods)
   adding your entry to ``index.json``. See ``../PUBLISHING.md`` for the full
   walkthrough.
"@
$readme | Out-File -FilePath (Join-Path $Target "README.md") -Encoding utf8

# Summary
Write-Host ""
Write-Host "Created $Target with:" -ForegroundColor Green
Get-ChildItem $Target | ForEach-Object { Write-Host "  $($_.Name)" }
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. cd $ShortName"
Write-Host "  2. Open index.js and write your mod logic."
Write-Host "  3. Test locally (see the generated README.md for the path)."
Write-Host "  4. When ready, follow PUBLISHING.md."
Write-Host ""
