#!/usr/bin/env bash
# new-mod.sh — scaffold a fresh Maker Studio mod folder.
#
# Usage:
#   ./scripts/new-mod.sh
#   ./scripts/new-mod.sh com.yourname.mymod "My Mod" "Your Name" "Short description."
#
# Creates ./<short-name>/ with manifest.json + index.js + README.md skeletons.

set -euo pipefail

MOD_ID="${1:-}"
NAME="${2:-}"
AUTHOR="${3:-}"
DESCRIPTION="${4:-}"
OUT_DIR="$(pwd)"

cyan()  { printf '\033[36m%s\033[0m\n' "$*"; }
yellow(){ printf '\033[33m%s\033[0m\n' "$*"; }
red()   { printf '\033[31m%s\033[0m\n' "$*"; }
green() { printf '\033[32m%s\033[0m\n' "$*"; }

require_input() {
    local var_name="$1"
    local prompt="$2"
    local value="${!var_name}"
    while [ -z "$value" ]; do
        read -r -p "$prompt: " value
        if [ -z "$value" ]; then yellow "  (required)"; fi
    done
    printf -v "$var_name" '%s' "$value"
}

echo
cyan "Maker Studio — new mod scaffolder"
echo

require_input MOD_ID  "Mod id (reverse-DNS, e.g. com.yourname.mymod)"
require_input NAME    "Display name (shown in Mod Manager)"
require_input AUTHOR  "Author (your display name)"
if [ -z "$DESCRIPTION" ]; then
    read -r -p "Description (one short sentence — optional): " DESCRIPTION
fi

if ! printf '%s' "$MOD_ID" | grep -qE '^[A-Za-z0-9._-]+$'; then
    red "Mod id has invalid characters. Allowed: letters, digits, '.', '_', '-'."
    exit 1
fi
if ! printf '%s' "$MOD_ID" | grep -q '\.'; then
    yellow "Mod id should look reverse-DNS (e.g. com.yourname.mymod)."
fi

SHORT_NAME="${MOD_ID##*.}"
TARGET="$OUT_DIR/$SHORT_NAME"

if [ -e "$TARGET" ]; then
    red "Target already exists: $TARGET"
    red "Move/remove it before re-running. Refusing to overwrite."
    exit 1
fi

mkdir -p "$TARGET"

# manifest.json
cat > "$TARGET/manifest.json" <<EOF
{
  "id": "$MOD_ID",
  "name": "$NAME",
  "version": "1.0.0",
  "author": "$AUTHOR",
  "description": "$DESCRIPTION",
  "apiVersion": "1.0.0",
  "main": "index.js",
  "permissions": ["ui.toasts"]
}
EOF

# index.js
cat > "$TARGET/index.js" <<EOF
/**
 * $NAME — $DESCRIPTION
 * Generated by scripts/new-mod.sh.
 */

export function activate(ctx) {
  ctx.log.info("$NAME activated");

  ctx.ui.showToast({
    message: "Hello from $NAME!",
    level: "info",
  });

  ctx.menu.registerMenuItem({
    menu: "Mods",
    label: "$NAME — Say Hi",
    handler: () => {
      ctx.ui.showToast({ message: "Hi from $NAME!" });
    },
  });
}

export function deactivate() {
  // Disposables registered through ctx are auto-cleaned. Nothing else to do.
}
EOF

# README.md
cat > "$TARGET/README.md" <<EOF
# $NAME

$DESCRIPTION

## Try it locally

1. Copy this folder into your global mods dir:
   - macOS: \`~/Library/Application Support/maker-studio/Mods/$SHORT_NAME/\`
   - Linux: \`~/.local/share/maker-studio/Mods/$SHORT_NAME/\`
   Or into a project's mods dir at \`<gameRoot>/Plugins/MakerStudio/003_Editor/Mods/$SHORT_NAME/\`.
2. Restart the editor (or **Mods → Mod Manager → Rescan**).
3. Open any project — toast appears, menu item shows up under **Mods**.

## Publish it

1. Push this folder to a public GitHub repo (one repo per mod).
2. Tag \`v1.0.0\` (must match \`manifest.json#version\`).
3. Build the release zip:
   \`\`\`bash
   zip -r $MOD_ID-1.0.0.zip manifest.json index.js README.md
   \`\`\`
4. Sign it (see \`../KEYS.md\` for keypair setup):
   \`\`\`bash
   minisign -S -s your-mod.key -m $MOD_ID-1.0.0.zip
   \`\`\`
5. Create a GitHub Release for the tag, attach both files.
6. Open a PR to the [registry](https://github.com/Toskan4134/maker-studio-mods)
   adding your entry to \`index.json\`. See \`../PUBLISHING.md\` for the full walkthrough.
EOF

# Summary
echo
green "Created $TARGET with:"
ls "$TARGET"
echo
cyan "Next steps:"
echo "  1. cd $SHORT_NAME"
echo "  2. Open index.js and write your mod logic."
echo "  3. Test locally (see the generated README.md for the path)."
echo "  4. When ready, follow PUBLISHING.md."
echo
